### ISSUE TITLE
godb: use community supported package globalsign/mgo

### ISSUE THREAD

**Issue by mgenov** [clouway/godb#21]
As existing implementation of mgo which is used by the library is no longer supported it is better the implementation to be switched to https://github.com/globalsign/mgo as it has larger community and provides a features related with the latest mongo releases.

**Comment by FeNoMeNa** [comment]
We should update this lib soon, it's quite possible the persistent failures on the jenkins to be related with the old lib.

**Comment by FeNoMeNa** [comment]
done
